[package]
name = "gemkernel"
version = "0.1.0"
authors = ["Tim Ryan <id@timryan.org>"]
edition = "2018"

[dependencies]
rand="*"
itertools = "*"
rayon = "*"
maplit="*"
serde_json="*"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3
